services:
  mongodb:
    image: mongo:latest
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_CONTAINER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER 
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:
    driver: local